const ACCOUNT = "/me";
const GET_ACCOUNT_PROFILE = ACCOUNT;
const UPDATE_AVATAR_PROFILE = ACCOUNT + "/avatar";
const UPDATE_INFO_PROFILE = ACCOUNT;
const GET_ACCOUNT_SELLER_PROFILE = ACCOUNT + "/seller-profile"
const UPDATE_INFO_SELLER_PROFILE = ACCOUNT + "/seller-profile"

export default {
  GET_ACCOUNT_PROFILE,
  UPDATE_AVATAR_PROFILE,
  UPDATE_INFO_PROFILE,
  GET_ACCOUNT_SELLER_PROFILE,
  UPDATE_INFO_SELLER_PROFILE
};
