const SELLER_STATISTICS = "/SellerStatistics";
const SELLER_STATISTICS_BY_ID = (sellerId: string) => `${SELLER_STATISTICS}/${sellerId}`;
const SELLER_STATISTICS_ME = `${SELLER_STATISTICS}/me`;
const SELLER_STATISTICS_OVERVIEW = `${SELLER_STATISTICS}/overview`;
const SELLER_STATISTICS_TOP_PRODUCTS = `${SELLER_STATISTICS}/top-products`;
const SELLER_STATISTICS_TOP_BLINDBOXES = `${SELLER_STATISTICS}/top-blindboxes`;
const SELLER_STATISTICS_ORDER_STATUS = `${SELLER_STATISTICS}/order-status`;
const SELLER_STATISTICS_TIME_SERIES = `${SELLER_STATISTICS}/time-series`;

export default {
  SELLER_STATISTICS,
  SELLER_STATISTICS_BY_ID,
  SELLER_STATISTICS_ME,
  SELLER_STATISTICS_OVERVIEW,
  SELLER_STATISTICS_TOP_PRODUCTS,
  SELLER_STATISTICS_TOP_BLINDBOXES,
  SELLER_STATISTICS_ORDER_STATUS,
  SELLER_STATISTICS_TIME_SERIES,
};
